import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { ThreatsProvider } from '@/src/context/threats-context/provider'

import { HeroesProvider } from '../context/heroes-context/provider'
import { envServer } from '../env/server'
import { HeroMapper } from '../mappers/hero-mapper'
import { APIResponseCollection } from '../types/strapi'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { data } = (await (
    await fetch(`${envServer.BASE_URL}/api/heroes`)
  ).json()) as APIResponseCollection<'api::hero.hero'>

  const heroes = data.map(HeroMapper.toClient)

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThreatsProvider>
          <HeroesProvider heroes={heroes}>{children}</HeroesProvider>
        </ThreatsProvider>
      </body>
    </html>
  )
}
