# Base image
FROM node:18

WORKDIR /app

ENV NODE_ENV=production
# ENV DATABASE_URL="postgresql://postgres:docker@localhost:5432/ihero?schema=public"
ENV HOST=0.0.0.0
ENV PORT=1337

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 1337

CMD npm run start
